### ISSUE TITLE
NPE when starting server

### ISSUE THREAD

**Issue by hunter688** [prism/Keys#13] opened 2016-02-28 09:06 UTC
http://pastebin.com/zbUF0pPn

Keys 1.0.1
SpongeForge build 1170

**Comment by viveleroi** [comment] 2016-02-28 15:25
What version of Forge/Minecraft?

**Comment by hunter688** [comment] 2016-02-28 17:03
MC 1.8.9, forge 11.15.1.1763

**Comment by viveleroi** [comment] 2016-02-29 16:36
I'm unable to reproduce this - what mods do you have? Something has removed a vanilla block type which is throwing an NPE in Minecraft.

Do you see anything in your log regarding "Skipping BlockTypes.ACACIA_DOOR"?

**Comment by hunter688** [comment] 2016-02-29 19:56
Ah, its maybe malisis doors mod...

**Comment by hunter688** [comment] 2016-02-29 19:59
When removed malisis doors error disappear. Malisis doors mod manipulate with vanilla doors(add animations for example)

**Comment by viveleroi** [comment] 2016-02-29 20:20
It sounds like however that mod changes the doors, it leaves invalid data and triggers the NPE. I'm discussing this now with the Sponge team but I'll close this issue because it doesn't appear to be anything wrong with Keys,

**Closed by viveleroi** 2016-02-29 20:20 UTC

**Comment by Ordinastie** [comment] 2016-03-02 15:38
I don't even have Block.getId() method in mappings, so it's a bit hard to debug...
